# ruff: noqa: E501

WORKBENCH_HTML = """<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'">
  <title>ScholarHarness · Workbench</title>
  <style>
    :root { color-scheme: dark; --ink:#101515; --deep:#151d1c; --panel:#1b2523; --panel2:#222e2b; --line:#34423e; --paper:#e8eadf; --muted:#91a09a; --cyan:#6ee7dd; --lime:#c5f467; --amber:#f4c56b; --red:#ff817a; --shadow:0 24px 70px #0005; font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif; }
    *{box-sizing:border-box} body{margin:0;background:var(--ink);color:var(--paper);min-height:100vh} body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.25;background-image:linear-gradient(#6ee7dd09 1px,transparent 1px),linear-gradient(90deg,#6ee7dd09 1px,transparent 1px);background-size:38px 38px;mask-image:linear-gradient(#000,transparent 78%)}
    button,input,select{font:inherit} button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid var(--cyan);outline-offset:3px}.shell{display:grid;grid-template-columns:250px minmax(0,1fr);min-height:100vh}.rail{position:sticky;top:0;height:100vh;padding:30px 22px;border-right:1px solid var(--line);background:#101515eb;backdrop-filter:blur(18px);z-index:2}.brand{display:flex;gap:12px;align-items:center;margin-bottom:40px}.brand-mark{display:grid;place-items:center;width:42px;height:42px;border:1px solid var(--cyan);border-radius:13px;color:var(--cyan);font:700 15px ui-monospace,monospace}.brand strong{display:block}.brand small,.muted{color:var(--muted)}nav{display:grid;gap:8px}.nav-button{border:0;background:transparent;color:var(--muted);text-align:left;padding:12px 14px;border-radius:11px;cursor:pointer}.nav-button:hover{color:var(--paper);background:var(--panel)}.nav-button[aria-current=page]{color:var(--ink);background:var(--lime);font-weight:700}.rail-foot{position:absolute;left:22px;right:22px;bottom:24px;color:var(--muted);font-size:12px;line-height:1.6}.rail-foot a{color:var(--cyan)}
    main{min-width:0;padding:34px clamp(22px,4vw,62px) 70px}.topbar{display:flex;justify-content:space-between;gap:22px;align-items:flex-end;margin-bottom:32px}.eyebrow{color:var(--cyan);text-transform:uppercase;letter-spacing:.16em;font:700 11px ui-monospace,monospace}h1{font-size:clamp(28px,4vw,48px);letter-spacing:-.045em;line-height:1;margin:9px 0 0}h2{margin:0;font-size:22px}h3{margin:0;font-size:15px}.service-state{display:flex;gap:9px;align-items:center;padding:9px 12px;background:var(--panel);border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:12px}.service-state i{width:8px;height:8px;border-radius:50%;background:var(--lime);box-shadow:0 0 14px var(--lime)}.section-head{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:18px}.section-head p{margin:5px 0 0;color:var(--muted);font-size:13px}
    .metrics{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr));gap:12px;margin-bottom:26px}.metric,.card{background:linear-gradient(145deg,#222e2bf0,#192220f0);border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow)}.metric{min-height:126px;padding:18px;display:flex;flex-direction:column;justify-content:space-between}.metric span{color:var(--muted);font-size:12px}.metric strong{font:650 34px ui-monospace,monospace;color:var(--paper)}.card{padding:20px}.split{display:grid;grid-template-columns:minmax(260px,.75fr) minmax(420px,1.6fr);gap:16px;align-items:start}.stack{display:grid;gap:10px}.list-button{width:100%;border:1px solid var(--line);background:var(--deep);color:var(--paper);padding:13px;border-radius:12px;text-align:left;cursor:pointer}.list-button:hover,.list-button.selected{border-color:var(--cyan);background:#6ee7dd14}.list-button small{color:var(--muted);display:block;margin-top:6px}.row{display:flex;justify-content:space-between;gap:14px;align-items:baseline}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.pill{display:inline-flex;padding:4px 8px;border-radius:999px;border:1px solid var(--line);color:var(--muted);font:700 10px ui-monospace,monospace;text-transform:uppercase}.pill.completed,.pill.confirmed{color:var(--lime)}.pill.running,.pill.candidate{color:var(--cyan)}.pill.failed,.pill.rejected{color:var(--red)}.pill.aborted,.pill.superseded{color:var(--amber)}
    .timeline{border-left:1px solid var(--line);margin-left:7px;padding-left:20px;display:grid;gap:12px}.timeline-item{position:relative;padding:14px;border-radius:12px;background:var(--deep);border:1px solid var(--line)}.timeline-item:before{content:"";position:absolute;left:-25px;top:19px;width:8px;height:8px;border-radius:50%;background:var(--cyan)}pre{white-space:pre-wrap;overflow-wrap:anywhere;margin:12px 0 0;padding:12px;background:#0d1212;border-radius:9px;color:#b9c9c3;font:11px/1.55 ui-monospace,monospace;max-height:300px;overflow:auto}.detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin:14px 0 20px}.detail-grid div{background:var(--deep);padding:10px;border-radius:9px;min-width:0}.detail-grid dt{color:var(--muted);font-size:10px;text-transform:uppercase}.detail-grid dd{margin:5px 0 0;overflow-wrap:anywhere;font:12px ui-monospace,monospace}.toolbar{display:flex;gap:9px;align-items:center;flex-wrap:wrap}input,select{background:var(--deep);color:var(--paper);border:1px solid var(--line);border-radius:10px;padding:10px 12px}input{min-width:min(320px,100%)}.action{border:1px solid var(--line);border-radius:10px;padding:10px 13px;background:var(--panel2);color:var(--paper);cursor:pointer}.action:hover{border-color:var(--cyan)}.action.primary{color:var(--ink);background:var(--lime);font-weight:700}.action.danger{color:var(--red)}.action:disabled{opacity:.5;cursor:wait}
    .memory-card,.paper-card,.result-card,.tool-card{border:1px solid var(--line);background:var(--deep);border-radius:13px;padding:15px}.memory-card p,.result-card p{line-height:1.6;color:#c9d1cc}blockquote{margin:12px 0;border-left:2px solid var(--amber);padding-left:12px;color:var(--muted);font-size:12px}.state{border:1px dashed var(--line);border-radius:13px;padding:20px;color:var(--muted);text-align:center}.state[data-kind=error]{color:var(--red)}.state[data-kind=loading]{color:var(--cyan)}.subhead{margin:24px 0 12px;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.1em}[hidden]{display:none!important}
    @media(max-width:1080px){.metrics{grid-template-columns:repeat(3,1fr)}.split{grid-template-columns:1fr}}@media(max-width:820px){.shell{display:block}.rail{position:relative;height:auto;padding:18px;border-right:0;border-bottom:1px solid var(--line)}.brand{margin-bottom:16px}nav{grid-template-columns:repeat(4,1fr)}.nav-button{text-align:center;padding:10px 6px}.rail-foot{display:none}main{padding:24px 16px 50px}.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){nav{grid-template-columns:repeat(2,1fr)}.topbar{display:block}.service-state{margin-top:18px;width:fit-content}.detail-grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}
  </style>
</head>
<body><div class="shell">
  <aside class="rail"><div class="brand"><div class="brand-mark">SH</div><div><strong>ScholarHarness</strong><small>research agent lab</small></div></div><nav aria-label="Workbench navigation"><button class="nav-button" data-route="overview" aria-current="page">总览</button><button class="nav-button" data-route="runs">运行追踪</button><button class="nav-button" data-route="memories">记忆审核</button><button class="nav-button" data-route="library">文献库</button></nav><div class="rail-foot">Local observability surface<br><a href="/docs">OpenAPI</a> · <a href="/health">Health</a></div></aside>
  <main><header class="topbar"><div><div class="eyebrow">Agent systems, made inspectable</div><h1 id="page-title">系统总览</h1></div><div class="service-state"><i></i><span id="service-label">localhost connected</span></div></header>
    <section data-page="overview"><div class="metrics"><article class="metric"><span>Agent runs</span><strong id="metric-runs">—</strong></article><article class="metric"><span>Tool calls</span><strong id="metric-tools">—</strong></article><article class="metric"><span>Candidate memory</span><strong id="metric-candidates">—</strong></article><article class="metric"><span>Confirmed memory</span><strong id="metric-confirmed">—</strong></article><article class="metric"><span>Papers</span><strong id="metric-papers">—</strong></article></div><article class="card"><div class="section-head"><div><h2>最近运行</h2><p>runtime-neutral trace projection</p></div><button class="action" data-go="runs">查看全部</button></div><div class="state" data-state="overview">等待加载</div><div class="stack" id="recent-runs"></div></article></section>
    <section data-page="runs" hidden><div class="section-head"><div><h2>运行追踪</h2><p>事件时间线与 correlated tool execution</p></div><button class="action" id="refresh-runs">刷新</button></div><div class="split"><article class="card"><div class="state" data-state="runs">等待加载</div><div class="stack" id="runs-list"></div></article><article class="card" id="run-detail"><div class="state" data-state="run-detail">选择一条运行</div></article></div></section>
    <section data-page="memories" hidden><div class="section-head"><div><h2>记忆审核</h2><p>Agent 提出 candidate；你决定可信上下文</p></div><div class="toolbar"><label for="memory-filter">状态</label><select id="memory-filter"><option value="candidate">candidate</option><option value="confirmed">confirmed</option><option value="rejected">rejected</option><option value="superseded">superseded</option><option value="">all</option></select><button class="action" id="refresh-memories">刷新</button></div></div><div class="state" data-state="memories">等待加载</div><div class="stack" id="memory-list"></div></section>
    <section data-page="library" hidden><div class="section-head"><div><h2>文献库</h2><p>检索结果保留 paper / passage / page 坐标</p></div><button class="action" id="refresh-library">刷新目录</button></div><article class="card"><form class="toolbar" id="search-form"><label for="search-query">检索</label><input id="search-query" required placeholder="memory provenance, tool use…"><label for="search-mode">模式</label><select id="search-mode"><option value="hybrid">hybrid</option><option value="lexical">lexical</option></select><button class="action primary" type="submit">搜索 passages</button></form><div class="state" data-state="search" hidden></div><div class="stack" id="search-results"></div></article><div class="subhead">Paper catalog</div><div class="state" data-state="library">等待加载</div><div class="stack" id="paper-list"></div></section>
  </main></div>
  <script type="module">
    const state={runs:[],memories:[],papers:[],selectedRun:null};const titles={overview:"系统总览",runs:"运行追踪",memories:"记忆审核",library:"文献库"};const byId=id=>document.getElementById(id);const make=(tag,className,text)=>{const item=document.createElement(tag);if(className)item.className=className;if(text!==undefined)item.textContent=String(text);return item};const clear=target=>target.replaceChildren();const pretty=value=>JSON.stringify(value,null,2);const time=value=>value?new Date(value).toLocaleString():"—";const badge=value=>make("span",`pill ${value||""}`,value||"unknown");
    function setPanelState(panel,kind,message,visible=true){const target=document.querySelector(`[data-state="${panel}"]`);target.dataset.kind=kind;target.textContent=message;target.hidden=!visible}
    async function request(path,options){const response=await fetch(path,options);if(!response.ok){let message=`${response.status} ${response.statusText}`;try{const body=await response.json();message=body.detail||message}catch(_){void _}throw new Error(message)}return response.json()}
    function runRow(run,clickable=false){const item=make(clickable?"button":"div",clickable?"list-button":"memory-card");if(clickable)item.type="button";const top=make("div","row");top.append(make("strong","mono",run.runtime_type),badge(run.status));item.append(top,make("small","mono",run.id),make("small","",`${time(run.started_at)} · leaf ${run.active_leaf_id||"—"}`));if(clickable)item.addEventListener("click",()=>selectRun(run.id));return item}
    async function loadOverview(){setPanelState("overview","loading","正在聚合 runs、tools、memories 与 papers…");try{const[runs,memories,papers]=await Promise.all([request("/runs?limit=100"),request("/memories?limit=500"),request("/papers?limit=500")]);const toolGroups=await Promise.all(runs.map(run=>request(`/runs/${encodeURIComponent(run.id)}/tools`).catch(()=>[])));state.runs=runs;state.memories=memories;state.papers=papers;byId("metric-runs").textContent=runs.length;byId("metric-tools").textContent=toolGroups.reduce((total,group)=>total+group.length,0);byId("metric-candidates").textContent=memories.filter(item=>item.status==="candidate").length;byId("metric-confirmed").textContent=memories.filter(item=>item.status==="confirmed").length;byId("metric-papers").textContent=papers.length;const recent=byId("recent-runs");clear(recent);runs.slice(0,6).forEach(run=>recent.append(runRow(run,true)));setPanelState("overview",runs.length?"ready":"empty",runs.length?"":"还没有 agent run。先运行 CLI chat 或 Pi。",!runs.length)}catch(error){setPanelState("overview","error",`总览加载失败：${error.message}`)}}
    async function loadRuns(){setPanelState("runs","loading","正在读取运行索引…");const list=byId("runs-list");clear(list);try{state.runs=await request("/runs?limit=100");state.runs.forEach(run=>list.append(runRow(run,true)));setPanelState("runs",state.runs.length?"ready":"empty",state.runs.length?"":"没有可检查的运行。",!state.runs.length);if(state.runs.length)await selectRun(state.selectedRun||state.runs[0].id)}catch(error){setPanelState("runs","error",`运行列表失败：${error.message}`)}}
    async function selectRun(runId){state.selectedRun=runId;const detail=byId("run-detail");setPanelState("run-detail","loading","正在读取事件和工具调用…");try{const[run,events,tools]=await Promise.all([request(`/runs/${encodeURIComponent(runId)}`),request(`/runs/${encodeURIComponent(runId)}/events`),request(`/runs/${encodeURIComponent(runId)}/tools`)]);clear(detail);const head=make("div","row");head.append(make("h2","",run.runtime_type),badge(run.status));detail.append(head);const fields=make("dl","detail-grid");[["run id",run.id],["started",time(run.started_at)],["ended",time(run.ended_at)],["active leaf",run.active_leaf_id||"—"],["session",run.external_session_id||"—"],["error",run.error||"—"]].forEach(([key,value])=>{const box=make("div");box.append(make("dt","",key),make("dd","",value));fields.append(box)});detail.append(fields,make("div","subhead",`Event timeline · ${events.length}`));const timeline=make("div","timeline");events.forEach(event=>{const item=make("article","timeline-item"),row=make("div","row");row.append(make("h3","mono",`${event.sequence}. ${event.event_type}`),make("span","muted mono",time(event.event_timestamp)));item.append(row);if(event.entry_id)item.append(make("div","muted mono",`entry ${event.entry_id}`));item.append(make("pre","",pretty(event.payload)));timeline.append(item)});detail.append(timeline,make("div","subhead",`Tool inspector · ${tools.length}`));const toolList=make("div","stack");tools.forEach(tool=>{const item=make("article","tool-card"),row=make("div","row");row.append(make("h3","mono",tool.tool_name),badge(tool.is_error?"failed":"completed"));item.append(row,make("div","muted mono",`${tool.tool_call_id} · ${tool.duration_ms??"—"} ms`),make("pre","",`arguments\n${pretty(tool.arguments)}\n\nresult\n${pretty(tool.result)}`));toolList.append(item)});if(!events.length)detail.append(make("div","state","该运行没有事件。"));if(!tools.length)toolList.append(make("div","state","该运行没有工具调用。"));detail.append(toolList)}catch(error){clear(detail);const panel=make("div","state",`运行详情失败：${error.message}`);panel.dataset.kind="error";detail.append(panel)}}
    async function loadMemories(){setPanelState("memories","loading","正在读取 memory trust store…");const list=byId("memory-list");clear(list);const status=byId("memory-filter").value,suffix=status?`?status=${encodeURIComponent(status)}&limit=500`:"?limit=500";try{const memories=await request(`/memories${suffix}`);state.memories=memories;memories.forEach(memory=>list.append(memoryCard(memory)));setPanelState("memories",memories.length?"ready":"empty",memories.length?"":"当前筛选没有记忆。",!memories.length)}catch(error){setPanelState("memories","error",`记忆加载失败：${error.message}`)}}
    function memoryCard(memory){const item=make("article","memory-card"),top=make("div","row");top.append(badge(memory.status),make("span","mono muted",`${memory.kind} · ${memory.scope} · ${Math.round(memory.confidence*100)}%`));item.append(top,make("p","",memory.content));memory.evidence.forEach(e=>item.append(make("blockquote","",`${e.paper_id} / ${e.passage_id}${e.page?` · p.${e.page}`:""}\n“${e.quote}”`)));const provenance=[memory.trace_run_id&&`run ${memory.trace_run_id}`,memory.source_tool_call_id&&`tool ${memory.source_tool_call_id}`].filter(Boolean).join(" · ");if(provenance)item.append(make("div","muted mono",provenance));if(memory.status==="candidate"){const actions=make("div","toolbar"),confirm=make("button","action primary","确认"),reject=make("button","action danger","拒绝");confirm.type=reject.type="button";confirm.addEventListener("click",()=>reviewMemory(memory.id,"confirm",[confirm,reject]));reject.addEventListener("click",()=>reviewMemory(memory.id,"reject",[confirm,reject]));actions.append(confirm,reject);item.append(actions)}return item}
    async function reviewMemory(memoryId,action,buttons){buttons.forEach(button=>{button.disabled=true});try{await request(`/memories/${encodeURIComponent(memoryId)}/${action}`,{method:"POST"});await Promise.all([loadMemories(),loadOverview()])}catch(error){setPanelState("memories","error",`审核失败：${error.message}`);buttons.forEach(button=>{button.disabled=false})}}
    async function loadLibrary(){setPanelState("library","loading","正在读取 paper catalog…");const list=byId("paper-list");clear(list);try{const papers=await request("/papers?limit=500");state.papers=papers;papers.forEach(paper=>{const item=make("article","paper-card"),top=make("div","row");top.append(make("h3","",paper.title),make("span","pill",`${paper.passage_count} passages`));item.append(top,make("div","muted",`${paper.authors.join(", ")||"Unknown authors"}${paper.year?` · ${paper.year}`:""}`),make("div","mono muted",paper.id));list.append(item)});setPanelState("library",papers.length?"ready":"empty",papers.length?"":"文献库为空，可通过 API 导入 PDF。",!papers.length)}catch(error){setPanelState("library","error",`目录加载失败：${error.message}`)}}
    async function searchLibrary(event){event.preventDefault();const query=byId("search-query").value.trim();if(!query)return;setPanelState("search","loading","正在执行检索…");const results=byId("search-results");clear(results);try{const body=await request("/internal/tools/search_papers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query,mode:byId("search-mode").value,limit:20})});body.items.forEach(hit=>{const item=make("article","result-card"),top=make("div","row");top.append(make("h3","",hit.title),make("span","pill",hit.retrieval_mode));item.append(top,make("div","mono muted",`${hit.paper_id} / ${hit.passage_id}${hit.page?` · p.${hit.page}`:""}`),make("p","",hit.text),make("div","mono muted",`score ${Number(hit.score).toFixed(5)} · lexical ${hit.lexical_rank??"—"} · vector ${hit.vector_rank??"—"}`));results.append(item)});setPanelState("search",body.items.length?"ready":"empty",body.items.length?"":"没有找到相关 passage。",!body.items.length)}catch(error){setPanelState("search","error",`检索失败：${error.message}`)}}
    async function navigate(route){document.querySelectorAll("[data-page]").forEach(page=>{page.hidden=page.dataset.page!==route});document.querySelectorAll("[data-route]").forEach(button=>{if(button.dataset.route===route)button.setAttribute("aria-current","page");else button.removeAttribute("aria-current")});byId("page-title").textContent=titles[route];if(route==="overview")await loadOverview();if(route==="runs")await loadRuns();if(route==="memories")await loadMemories();if(route==="library")await loadLibrary()}
    document.querySelectorAll("[data-route]").forEach(button=>button.addEventListener("click",()=>navigate(button.dataset.route)));document.querySelectorAll("[data-go]").forEach(button=>button.addEventListener("click",()=>navigate(button.dataset.go)));byId("refresh-runs").addEventListener("click",loadRuns);byId("refresh-memories").addEventListener("click",loadMemories);byId("memory-filter").addEventListener("change",loadMemories);byId("refresh-library").addEventListener("click",loadLibrary);byId("search-form").addEventListener("submit",searchLibrary);request("/health").catch(()=>{byId("service-label").textContent="service unavailable"});navigate("overview");
  </script>
</body></html>
"""
